<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Battle</title>
    <link rel="stylesheet" href="style_battle.css">
    <script src="./battle403.js"></script>
</head>
<body>
    <div class="container">
        <input class="arrow" type="image" src="https://files.axshare.com/gsc/2AGZYF/88/23/38/882338d60123458087e0059e88a96f0b/images/2_%D1%80%D0%BE%D0%B7%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F_%D0%BA%D0%BE%D1%80%D0%B0%D0%B1%D0%BB%D1%96%D0%B2/u167.svg?pageId=0d222dba-97fa-419f-b4e4-70003c8acabd" alt="Вихід в головне меню" onclick="window.location.href='https://fmc2.avmg.com.ua/study/beheza/test2/seabattle/acc/acc.php'">
        <img class="img-ship" src="https://files.axshare.com/gsc/2AGZYF/88/23/38/882338d60123458087e0059e88a96f0b/images/2_%D1%80%D0%BE%D0%B7%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F_%D0%BA%D0%BE%D1%80%D0%B0%D0%B1%D0%BB%D1%96%D0%B2/u192.svg?pageId=0d222dba-97fa-419f-b4e4-70003c8acabd" alt="">
        <p class="title">Морський бій</p>
        <input class="cross" type="image" src="https://files.axshare.com/gsc/2AGZYF/88/23/38/882338d60123458087e0059e88a96f0b/images/2_%D1%80%D0%BE%D0%B7%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F_%D0%BA%D0%BE%D1%80%D0%B0%D0%B1%D0%BB%D1%96%D0%B2/u166.svg?pageId=0d222dba-97fa-419f-b4e4-70003c8acabd" alt="" onclick="window.location.href='https://fmc2.avmg.com.ua/study/beheza/test2/seabattle/acc/acc.php'">
        <img class="img-time" src="https://files.axshare.com/gsc/2AGZYF/88/23/38/882338d60123458087e0059e88a96f0b/images/3_%D0%B1%D1%96%D0%B9/u314.svg?pageId=24ccf788-4b6d-4a2d-83de-525ad6b4cc8a" alt="">
        <span class="text-time">час на хід</span>
        <span class="time">30 сек</span>
        <span class="text1-skip-move">Залишилось пропусків ходу</span>
        <span class="text2-skip-move">Залишилось пропусків ходу</span>
        <img class="skip-move1" src="https://files.axshare.com/gsc/2AGZYF/88/23/38/882338d60123458087e0059e88a96f0b/images/3_%D0%B1%D1%96%D0%B9/u327.svg?pageId=24ccf788-4b6d-4a2d-83de-525ad6b4cc8a" alt="">
        <span class="user1-skip-move">3</span>
        <img class="skip-move2" src="https://files.axshare.com/gsc/2AGZYF/88/23/38/882338d60123458087e0059e88a96f0b/images/3_%D0%B1%D1%96%D0%B9/u327.svg?pageId=24ccf788-4b6d-4a2d-83de-525ad6b4cc8a" alt="">
        <span class="user2-skip-move">3</span>
        <span class="move">Хід</span>
        <div class="container-user-login">
            <p class="user-login"></p>
        </div>
        <div class="container-opponent-login">
            <p class="opponent-login"></p>
        </div>
        <span class="user-A coordinate user-X">A</span>
        <span class="user-B coordinate user-X">B</span>
        <span class="user-C coordinate user-X">C</span>
        <span class="user-D coordinate user-X">D</span>
        <span class="user-E coordinate user-X">E</span>
        <span class="user-F coordinate user-X">F</span>
        <span class="user-G coordinate user-X">G</span>
        <span class="user-H coordinate user-X">H</span>
        <span class="user-I coordinate user-X">I</span>
        <span class="user-J coordinate user-X">J</span>
        <span class="user-Y-1 coordinate user-Y">1</span>
        <span class="user-Y-2 coordinate user-Y">2</span>
        <span class="user-Y-3 coordinate user-Y">3</span>
        <span class="user-Y-4 coordinate user-Y">4</span>
        <span class="user-Y-5 coordinate user-Y">5</span>
        <span class="user-Y-6 coordinate user-Y">6</span>
        <span class="user-Y-7 coordinate user-Y">7</span>
        <span class="user-Y-8 coordinate user-Y">8</span>
        <span class="user-Y-9 coordinate user-Y">9</span>
        <span class="user-Y-10 coordinate user-Y">10</span>
        <div class="user-battle-field">
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil ceil-10 last-ceil"></div>
        </div>


        <span class="opponent-A coordinate opponent-X">A</span>
        <span class="opponent-B coordinate opponent-X">B</span>
        <span class="opponent-C coordinate opponent-X">C</span>
        <span class="opponent-D coordinate opponent-X">D</span>
        <span class="opponent-E coordinate opponent-X">E</span>
        <span class="opponent-F coordinate opponent-X">F</span>
        <span class="opponent-G coordinate opponent-X">G</span>
        <span class="opponent-H coordinate opponent-X">H</span>
        <span class="opponent-I coordinate opponent-X">I</span>
        <span class="opponent-J coordinate opponent-X">J</span>
        <span class="opponent-Y-1 coordinate opponent-Y">1</span>
        <span class="opponent-Y-2 coordinate opponent-Y">2</span>
        <span class="opponent-Y-3 coordinate opponent-Y">3</span>
        <span class="opponent-Y-4 coordinate opponent-Y">4</span>
        <span class="opponent-Y-5 coordinate opponent-Y">5</span>
        <span class="opponent-Y-6 coordinate opponent-Y">6</span>
        <span class="opponent-Y-7 coordinate opponent-Y">7</span>
        <span class="opponent-Y-8 coordinate opponent-Y">8</span>
        <span class="opponent-Y-9 coordinate opponent-Y">9</span>
        <span class="opponent-Y-10 coordinate opponent-Y">10</span>
        <div class="opponent-battle-field">
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil"></div>
            <div class="ceil ceil-10"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil last-ceil"></div>
            <div class="ceil ceil-10 last-ceil"></div>
        </div>
        <div class="version">
            <p>v1.0</p>
        </div>
    </div>

    <script src="./script_battle.js"></script>
</body>
</html>